<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYxx4Oen\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYxx4Oen/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYxx4Oen.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYxx4Oen\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerYxx4Oen\appAppKernelDevDebugContainer([
    'container.build_hash' => 'Yxx4Oen',
    'container.build_id' => 'c5d14131',
    'container.build_time' => 1685984504,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYxx4Oen');
